overrides:
  '@angular/router': 22.1.3
  '@angular/platform-server': 22.1.3
  '@angular/platform-browser-dynamic': 22.1.3
  '@angular/platform-browser': 22.1.3
  '@angular/forms': 22.1.3
  '@angular/core': 22.1.3
  '@angular/compiler': 22.1.3
  '@angular/common': 22.1.3
  '@angular/animations': 22.1.3
  '@sneat/api-firebase-auth': 0.27.11
  '@sneat/api-public': 0.27.11
  '@sneat/api': 0.27.11
  '@sneat/app-auth': 0.27.11
  '@sneat/app-ionic': 0.27.11
  '@sneat/app-public': 0.27.11
  '@sneat/app': 0.27.11
  '@sneat/auth-core': 0.27.11
  '@sneat/auth-models': 0.27.11
  '@sneat/auth-ui': 0.27.11
  '@sneat/components': 0.27.11
  '@sneat/core-public': 0.27.11
  '@sneat/core': 0.27.11
  '@sneat/data': 0.27.11
  '@sneat/datagrid': 0.27.11
  '@sneat/dto': 0.27.11
  '@sneat/extension-calendarius-contract': 0.27.4
  '@sneat/extension-calendarius-internal': 0.27.2
  '@sneat/extension-calendarius-shared': 0.27.2
  '@sneat/grid': 0.27.11
  '@sneat/logging': 0.27.11
  '@sneat/space-components': 0.27.11
  '@sneat/space-models': 0.27.11
  '@sneat/space-nav-ionic': 0.27.11
  '@sneat/space-nav-router': 0.27.11
  '@sneat/space-services': 0.27.11
  '@sneat/ui': 0.27.11
  '@sneat/wizard': 0.27.11
packages:
  - '.'

allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  protobufjs: true

minimumReleaseAgeExclude:
  - '@sneat/api-firebase-auth@0.26.4 || 0.27.11'
  - '@sneat/api-public@0.26.4 || 0.27.11'
  - '@sneat/api@0.26.4 || 0.27.11'
  - '@sneat/app-auth@0.26.4 || 0.27.11'
  - '@sneat/app-ionic@0.26.4 || 0.27.11'
  - '@sneat/app-public@0.26.4 || 0.27.11'
  - '@sneat/app@0.26.4 || 0.27.11'
  - '@sneat/auth-core@0.26.4 || 0.27.11'
  - '@sneat/auth-models@0.26.4 || 0.27.11'
  - '@sneat/auth-ui@0.26.4 || 0.27.11'
  - '@sneat/core-public@0.26.4 || 0.27.11'
  - '@sneat/core@0.26.4 || 0.27.11'
  - '@sneat/dto@0.26.4 || 0.27.11'
  - '@sneat/logging@0.26.4 || 0.27.11'
  - '@sneat/space-services@0.26.4 || 0.27.11'
  - '@sneat/ui@0.26.4 || 0.27.11'
